# Generated by Django 2.0.7 on 2018-10-29 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accomodation',
            fields=[
                ('aid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=1024)),
                ('atype', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='accomodationfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.accomodation')),
            ],
        ),
        migrations.CreateModel(
            name='airway',
            fields=[
                ('aiid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=1024)),
                ('aclass', models.CharField(max_length=1024)),
                ('name', models.CharField(default='air india', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('bid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.accomodation')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='kalyanshiva98@gmail.com', max_length=254)),
                ('username', models.CharField(default='kalyanshiva', max_length=1024)),
                ('cname', models.CharField(max_length=1024)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('password', models.CharField(max_length=50)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('eid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('etype', models.CharField(max_length=1024)),
                ('starttime', models.TimeField(auto_now_add=True)),
                ('endtime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventsof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.events')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('pno', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('pcost', models.IntegerField(default=1)),
                ('noofpass', models.IntegerField(default=1)),
                ('pname', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='payby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('mode', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('eprice', models.IntegerField(default=1)),
                ('oprice', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='placeby',
            fields=[
                ('pid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(default='INDIA')),
            ],
        ),
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.accomodation')),
            ],
        ),
        migrations.CreateModel(
            name='restaraunt',
            fields=[
                ('rid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('rtype', models.CharField(max_length=1024)),
                ('starttime', models.TimeField(auto_now_add=True)),
                ('endtime', models.TimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='roadway',
            fields=[
                ('roid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=1024)),
                ('rotype', models.CharField(max_length=1024)),
                ('name', models.CharField(default='morning star', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='transportation',
            fields=[
                ('tid', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='transportationfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.placeby')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='waterway',
            fields=[
                ('wid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=1024)),
                ('wclass', models.CharField(max_length=1024)),
                ('name', models.CharField(default='Titanic', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.restaraunt'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.transportation'),
        ),
        migrations.AddField(
            model_name='payby',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.payment'),
        ),
        migrations.AddField(
            model_name='payby',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.placeby'),
        ),
        migrations.AddField(
            model_name='payby',
            name='pno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.package'),
        ),
        migrations.AddField(
            model_name='eventsof',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.placeby'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.package'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='rid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.restaraunt'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.transportation'),
        ),
        migrations.AddField(
            model_name='accomodationfor',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.placeby'),
        ),
    ]
